version : "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: P@ssW0rd
    ports:
      - 1433:1433
  redis:
    image: redis